[package]
<<<<<<< HEAD
name = "zcash-cxx"
version = "1.0.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
cxx = { version = "1.0", features = [ "alloc", "std" ] }
orchard = { version = "0.7.1",  default-features = false }

[lib]
name = "brave_wallet_cxx"
path = "lib.rs"
=======
name = "zcash"
description = "Zcash stuff"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
incrementalmerkletree = { features = ["legacy-api"] }

[lib]
name = "zcash"
>>>>>>> f07e752de92 (Implement shielding)
crate-type = ["rlib"]
