[package]
name = "ipfs-cxx"
description = "IPFS trustless blocks verification"
version = "1.0.0"
edition = "2021"
publish = false
license = "MPL-2.0"

[dependencies]
thiserror="1.0.38"
libipld="0.16.0"
libipld-core="0.16.0"
libipld-cbor="0.16.0"
libipld-pb="0.16.0"
libipld-json="0.16.0"
quick-protobuf="0.8.1"
murmur3 = "0.5.2"

[lib]
name = "ipfs_cxx"
crate-type = ["rlib"]
